[package]
rust-version.workspace = true
name = "sdkwork-content-documents-service"
version.workspace = true
edition.workspace = true


[lints]
workspace = true
[dependencies]
async-trait.workspace = true
sdkwork-documents-contract.workspace = true
sdkwork-utils-rust.workspace = true

[dev-dependencies]
tokio.workspace = true
