[package]
rust-version.workspace = true
name = "sdkwork-routes-documents-app-api"
version.workspace = true
edition.workspace = true
license.workspace = true


[lints]
workspace = true
[dependencies]
sdkwork-database-sqlx.workspace = true
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
sdkwork-content-documents-repository-sqlx.workspace = true
sdkwork-content-documents-service.workspace = true
sdkwork-content-documents-sdk-reference.workspace = true
sdkwork-documents-contract.workspace = true
sdkwork-documents-database-host.workspace = true
sdkwork-routes-documents-backend-api.workspace = true
sdkwork-routes-documents-open-api.workspace = true
sdkwork-iam-web-adapter.workspace = true
sdkwork-web-axum.workspace = true
sdkwork-web-core.workspace = true

[dev-dependencies]
async-trait.workspace = true
tokio.workspace = true
tower.workspace = true
