[package]
rust-version.workspace = true
name = "sdkwork-api-documents-standalone-gateway"
version.workspace = true
edition.workspace = true
license.workspace = true


[lints]
workspace = true
[lib]
path = "src/lib.rs"

[[bin]]
name = "sdkwork-api-documents-standalone-gateway"
path = "src/bin/app_main.rs"

[dependencies]
sdkwork_api_documents_assembly.workspace = true
axum.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "net", "signal"] }
tracing.workspace = true
tracing-subscriber.workspace = true
sdkwork-documents-observability.workspace = true
sdkwork-iam-web-adapter.workspace = true
sdkwork-web-bootstrap.workspace = true
